//! Outbound Telegram Bot API alerts (research notifications only).
//!
//! The Bot API is OUTBOUND ONLY: public-channel ingestion uses MTProto. Alert
//! text is generated by the service; untrusted Telegram content never flows
//! into alert commands.

#![allow(dead_code)]  // planned API surface; runtime wiring lands with the workers

use anyhow::{anyhow, Result};

/// An outbound alert message.
#[derive(Clone, Debug)]
pub struct AlertMessage {
    pub dedup_key: String,
    pub text: String,
}

/// Compose a research alert message. Wording rules:
/// - funding alerts say `possible project preparation`; never `insider` or
///   `project confirmed`.
pub fn compose_signal_alert(
    chain: &str,
    mint: &str,
    kind: &str,
    score: u32,
    evidence_summary: &str,
) -> AlertMessage {
    let text = format!(
        "[{kind}] {chain} {mint} score {score}\n{evidence_summary}\nResearch signal; not financial advice."
    );
    AlertMessage {
        dedup_key: format!("signal:{chain}:{mint}:{kind}"),
        text,
    }
}

pub fn compose_funding_alert(recipient: &str, chain: &str, confidence: u32, summary: &str) -> AlertMessage {
    let text = format!(
        "[funding_radar] {chain} wallet {recipient} confidence {confidence}: possible project preparation\n{summary}"
    );
    AlertMessage {
        dedup_key: format!("funding:{chain}:{recipient}"),
        text,
    }
}

/// Send a message through the Bot API `sendMessage`.
pub async fn send_message(
    http: &reqwest::Client,
    bot_token: &str,
    chat_id: &str,
    text: &str,
) -> Result<()> {
    let url = format!("https://api.telegram.org/bot{bot_token}/sendMessage");
    let response = http
        .post(&url)
        .json(&serde_json::json!({
            "chat_id": chat_id,
            "text": text,
            "disable_web_page_preview": true,
        }))
        .send()
        .await
        .map_err(|e| anyhow!("telegram send failed: {e}"))?;
    if !response.status().is_success() {
        let status = response.status();
        return Err(anyhow!("telegram send failed with status {status}"));
    }
    Ok(())
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn signal_alert_wording() {
        let alert = compose_signal_alert("solana", "MINT", "entry", 75, "two clusters");
        assert!(alert.text.contains("entry"));
        assert!(alert.text.contains("MINT"));
        assert!(alert.text.contains("not financial advice"));
        assert_eq!(alert.dedup_key, "signal:solana:MINT:entry");
    }

    #[test]
    fn funding_alert_wording_never_claims_insider() {
        let alert = compose_funding_alert("Wallet", "solana", 80, "fanout evidence");
        let lower = alert.text.to_lowercase();
        assert!(lower.contains("possible project preparation"));
        assert!(!lower.contains("insider"));
        assert!(!lower.contains("project confirmed"));
        assert_eq!(alert.dedup_key, "funding:solana:Wallet");
    }
}
