//! Outbound Telegram Bot API alerts (research notifications only).
//!
//! The Bot API is OUTBOUND ONLY: public-channel ingestion uses MTProto. Alert
//! text is generated by the service; untrusted Telegram content never flows
//! into alert commands.

#![allow(dead_code)]  // planned API surface; runtime wiring lands with the workers


/// An outbound alert message.
#[derive(Clone, Debug)]
pub struct AlertMessage {
    pub dedup_key: String,
    pub text: String,
}

/// Compose a research alert message. Wording rules:
/// - funding alerts say `possible project preparation`; never `insider` or
///   `project confirmed`.
pub fn compose_signal_alert(
    chain: &str,
    mint: &str,
    kind: &str,
    score: u32,
    evidence_summary: &str,
) -> AlertMessage {
    let text = format!(
        "[{kind}] {chain} {mint} score {score}\n{evidence_summary}\nResearch signal; not financial advice."
    );
    AlertMessage {
        dedup_key: format!("signal:{chain}:{mint}:{kind}"),
        text,
    }
}

pub fn compose_funding_alert(recipient: &str, chain: &str, confidence: u32, summary: &str) -> AlertMessage {
    let text = format!(
        "[funding_radar] {chain} wallet {recipient} confidence {confidence}: possible project preparation\n{summary}"
    );
    AlertMessage {
        dedup_key: format!("funding:{chain}:{recipient}"),
        text,
    }
}

/// The endpoint the Bot API call goes to.
///
/// REV-074-F03: a parameter rather than a hardcoded host, because the delivery
/// retry semantics must be testable without contacting the real Telegram API — a
/// test that cannot force a 500-then-200 sequence cannot prove retry at all.
/// Production passes `TELEGRAM_BOT_API_BASE`.
pub const TELEGRAM_BOT_API_BASE: &str = "https://api.telegram.org";

/// How a failed send is classified for the outbox (REV-074-F03).
#[derive(Clone, Copy, Debug, PartialEq, Eq)]
pub enum SendFailure {
    /// 429 with Retry-After — retry after the server-provided delay.
    RateLimited(u64),
    /// Timeout/5xx/transport — retryable with backoff.
    Transient,
    /// Other 4xx — permanent; retrying cannot help.
    Permanent,
}

/// Send a message through the Bot API `sendMessage`.
///
/// Returns `Ok(())` on 2xx, `Err(SendFailure)` otherwise. The distinction is the
/// outbox contract: only `Ok` may mark a row sent.
pub async fn send_message(
    http: &reqwest::Client,
    bot_api_base: &str,
    bot_token: &str,
    chat_id: &str,
    text: &str,
) -> std::result::Result<(), SendFailure> {
    let url = format!("{bot_api_base}/bot{bot_token}/sendMessage");
    let response = http
        .post(&url)
        .json(&serde_json::json!({
            "chat_id": chat_id,
            "text": text,
            "disable_web_page_preview": true,
        }))
        .send()
        .await
        .map_err(|_| SendFailure::Transient)?;
    let status = response.status();
    if status.is_success() {
        // REV-076-F03: the Bot API answers 200 with `{"ok":false,...}` for some
        // errors. HTTP success is transport, not delivery: only `ok == true`
        // counts, and anything else is a permanent failure (retrying a rejected
        // request cannot help).
        let body: serde_json::Value = response
            .json()
            .await
            .map_err(|_| SendFailure::Transient)?;
        if body.get("ok").and_then(|v| v.as_bool()) == Some(true) {
            return Ok(());
        }
        return Err(SendFailure::Permanent);
    }
    if status == reqwest::StatusCode::TOO_MANY_REQUESTS {
        let retry_after = response
            .headers()
            .get(reqwest::header::RETRY_AFTER)
            .and_then(|v| v.to_str().ok())
            .and_then(|v| v.parse::<u64>().ok())
            .unwrap_or(30);
        return Err(SendFailure::RateLimited(retry_after));
    }
    if status.is_server_error() {
        return Err(SendFailure::Transient);
    }
    Err(SendFailure::Permanent)
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn signal_alert_wording() {
        let alert = compose_signal_alert("solana", "MINT", "entry", 75, "two clusters");
        assert!(alert.text.contains("entry"));
        assert!(alert.text.contains("MINT"));
        assert!(alert.text.contains("not financial advice"));
        assert_eq!(alert.dedup_key, "signal:solana:MINT:entry");
    }

    #[test]
    fn funding_alert_wording_never_claims_insider() {
        let alert = compose_funding_alert("Wallet", "solana", 80, "fanout evidence");
        let lower = alert.text.to_lowercase();
        assert!(lower.contains("possible project preparation"));
        assert!(!lower.contains("insider"));
        assert!(!lower.contains("project confirmed"));
        assert_eq!(alert.dedup_key, "funding:solana:Wallet");
    }
}
